apiVersion: 1
datasources:
  - name: Platform PostgreSQL
    type: postgres
    access: proxy
    url: ${GRAFANA_POSTGRES_HOST}:${GRAFANA_POSTGRES_PORT}
    user: ${GRAFANA_POSTGRES_USER}
    secureJsonData:
      password: ${GRAFANA_POSTGRES_PASSWORD}
    jsonData:
      database: ${GRAFANA_POSTGRES_DB}
      sslmode: ${GRAFANA_POSTGRES_SSLMODE}
      postgresVersion: 1700
      timescaledb: false
